# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
latex: false

r:
  - release

before_script:
  - sudo apt update 
  - sudo apt install -qq libgtk2.0-dev xorg-dev
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start

repos:
  docker: https://r.docker.stat.auckland.ac.nz

apt_packages:
  - libgtk2.0-dev
  - xorg-dev
  - libxml2-dev
  - libnlopt-dev
  - r-cran-rodbc
  - r-cran-rgtk2
  - r-cran-cairodevice

