# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: 
  - packages
  - directories:
    - $HOME/Library/Caches/Homebrew
latex: false
pandoc: false

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: 3.3
  allow_failures:
    - os: osx

repos:
  docker: https://r.docker.stat.auckland.ac.nz


addons:
  apt:
    update: true
    packages:
      - libgtk2.0-dev
      - xorg-dev
      - libxml2-dev
      - libnlopt-dev
      - r-cran-rodbc
      - r-cran-rgtk2
      - r-cran-cairodevice
  homebrew:
    packages:
      - libgit2

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then 
      sudo chown -R $(whoami) /usr/local/share;
      brew uninstall --force cairo --ignore-dependencies;
      brew cask install xquartz;
      brew install --with-x11 cairo;
      brew install gtk+;
    else
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 10; 
    fi

after_success:
  - Rscript -e 'covr::codecov()'

before_cache:
  - brew cleanup
