# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true

r:
  - release

repos:
  docker: http://r.docker.stat.auckland.ac.nz/R

apt_packages:
  - libgtk2.0-dev
  - xorg-dev
  - libxml2-dev
  - libnlopt-dev
  - r-cran-rodbc
  - r-cran-rgtk2
  - r-cran-cairodevice

